[package]
name = "client"
description = "client"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.62"
protocol = { path = "../protocol" }
js-sys = "0.3.39"
serde = { version = "1.0.106", features = ["rc"] }
serde_json = "1.0.52"
flate2 = "1.0.14"
base64 = "0.12.0"
yew = "0.15.0"
hex = "0.4.2"
anyhow = "1.0.28"
wasm-bindgen-futures = "0.4.12"
console_error_panic_hook = "0.1.6"
bincode = "1.2.1"
futures = "0.3.4"
uuid = "0.8.1"

[dependencies.web-sys]
version = "0.3.39"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'Node',
  "NodeList",
  "console",
  "CloseEvent",
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
  "Location",
  "Navigator",
  "EventTarget",
  "AddEventListenerOptions",
  "Event",
  "Storage",
  "Crypto",
  "SubtleCrypto",
  "CryptoKey",
  "CryptoKeyPair",
  "BinaryType",
  "FormData",
  "HtmlFormElement",
  "HtmlAnchorElement",
  "HtmlAudioElement",
  "UrlSearchParams",
  "History",
  "ScrollRestoration",
  "DomTokenList",
  "Selection",
  "HtmlInputElement",
  "HtmlTextAreaElement",
  "CssStyleDeclaration",
]
