dist: focal
services:
  - docker
  - postgresql
before_install:
  - psql -U postgres -c "alter user postgres with password 'postgres';"
  - psql -U postgres -c "create database meguca;"
script:
  - docker pull bakape/meguca:latest
  - docker build --cache-from bakape/meguca:latest -t meguca .
  - docker run --rm --network host -e CI=true meguca make test TEST_DB="postgres://postgres:postgres@localhost:5432/meguca"
