dist: focal
services:
  - docker
  - postgresql
cache:
  directories:
    - docker_images
before_install:
  - (gunzip | docker load) < docker_images/meguca.img.gz || true
  - psql -U postgres -c "alter user postgres with password 'postgres';"
  - psql -U postgres -c "create database meguca;"
before_cache:
  - docker save meguca | gzip -1 > docker_images/meguca.img.gz
script:
  - docker pull bakape/meguca-dev:latest
  - docker build --cache-from bakape/meguca-dev:latest --cache-from meguca -t meguca .
  - docker run --rm --network host -e CI=true -e TEST_DB="postgres://postgres:postgres@localhost:5432/meguca" --entrypoint="" meguca make test
