services:
  - docker
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
install:
  - psql -c 'create database meguca;' -U postgres
script:
  - docker build -t meguca_test .
  - docker run --rm --network host -e CI=true meguca_test make test TEST_DB="postgres://postgres@localhost:5432/meguca"
