dist: bionic
services:
  - docker
cache:
  directories:
    - docker_images
before_install:
  - (gunzip | docker load) < docker_images/meguca.img.gz || true
before_cache:
  - docker save meguca | gzip -1 > docker_images/meguca.img.gz
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
install:
  - psql -c 'create database meguca;' -U postgres
script:
  - docker build -t meguca .
  - docker run --rm --network host -e CI=true meguca make test TEST_DB="postgres://postgres@localhost:5432/meguca"
