dist: focal
services:
  - docker
  - postgresql
before_install:
  - psql -U postgres -c "alter user postgres with password 'postgres';"
  - psql -U postgres -c "create database meguca;"
script:
  - docker pull bakape/meguca-dev:latest
  - docker build --cache-from bakape/meguca-dev:latest -t meguca .
  - docker run --rm --network host -e CI=true -e TEST_DB="postgres://postgres:postgres@localhost:5432/meguca" --entrypoint="" meguca make test
