name: On commit checks
on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Create DB
        run: psql postgres://postgres:postgres@postgres:5432/postgres -c "create database meguca;"
      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build --cache-from bakape/meguca-dev:latest -t meguca .
      - name: Run Rust tests
        run: docker run --rm --network host -e CI=true -e TEST_DB="postgres://postgres:postgres@postgres:5432/meguca" --entrypoint="" cargo test
      - name: Run Go tests
        run: docker run --rm --network host -e CI=true -e TEST_DB="postgres://postgres:postgres@postgres:5432/meguca" --entrypoint="" meguca make test
# TODO: code vetting
